const mongoose = require('mongoose');
const { Schema, model } = mongoose;

/**
 * QuestionBank Schema
 * Stores individual questions — either extracted from old exams or generated by AI.
 * Supports student reporting for hallucination flagging and moderation workflows.
 */
const questionBankSchema = new Schema({
  // The specific lecture / material file this question belongs to
  materialFileId: {
    type: Schema.Types.ObjectId,
    ref: 'MaterialFile',
    index: true
  },

  courseId: {
    type: Schema.Types.ObjectId,
    ref: 'Course',
    required: true,
    index: true
  },

  questionText: {
    type: String,
    required: true
  },

  // Answer choices for MCQ-type questions
  options: [{
    type: String,
    trim: true
  }],

  correctAnswer: {
    type: String,
    required: true
  },

  // Difficulty rating on a 1-5 scale
  difficulty: {
    type: Number,
    min: 1,
    max: 5
  },

  // Origin of the question
  source: {
    type: String,
    enum: ['extracted_from_exam', 'ai_generated'],
    required: true,
    index: true
  },

  // Confidence score from the AI model (0-100), applicable only when source is 'ai_generated'
  aiConfidenceScore: {
    type: Number,
    min: 0,
    max: 100
  },

  // Flagged by students for potential hallucinations or inaccuracies
  isReported: {
    type: Boolean,
    default: false
  },

  // Moderation status for the question lifecycle
  status: {
    type: String,
    enum: ['pending', 'ready', 'flagged'],
    default: 'ready',
    index: true
  }
}, {
  timestamps: true
});

module.exports = model('QuestionBank', questionBankSchema);
